### ISSUE TITLE
Refactor welcome email logic

### ISSUE THREAD

**Issue by jessykate** [embassynetwork/modernomad#122]
This logic is currently in at least 4 places. Also we may have issues with timezones since the code is using datetime.date.today() which we should make timezone aware.

There are some additional paths to the welcome emails not going out since they are often 4 lines in a try block. And if there is an error charging the card then the email won't go out. 

This can and should all be refactored so it's MUCH less kludgy.

**Comment by bfirsh** [comment]
Error charging card has been fixed, IIRC? I think the only remaining issue, besides it being a bit kludgy, is the timezone problem, which I have filed in more detail here: #587
