### ISSUE TITLE
log rotation script creating new files owned by root

### ISSUE THREAD

**Issue by jessykate** [embassynetwork/modernomad#177]
when i cycled gunicorn today it failed. i checked the gunicorn.log file and it was logging the error:

```
Error: Error: '/home/embassynetwork/logs/gunicorn.log' isn't writable [IOError(13, 'Permission denied')]
```

I checked the logdir and the file was owned by root. it looks like the file was cycled recently. i changed the log file to be owned by embassynetwork user (as with the previous versions .1 and .2) and all is now good. 

this could be a symptom of something else but i'm guessing the permissions just aren't being created quite right in the log rotation script. @jsayles where did you set that all up again?

**Comment by jonathan-s** [comment]
Now using sentry for logging so closing this. See #328 and #347
