### ISSUE TITLE
Location uses old get_model methods

### ISSUE THREAD

**Issue by jsayles** [embassynetwork/modernomad#222]
The way we are getting the Location model uses django.db.models.loading and that is deprecated in favor of the new application loading system.  

For an example of the fix we need to do:
http://stackoverflow.com/a/26126935

**Comment by jsayles** [comment]
This fix is a little more complex because it requires backing out of all the gather.Location vs core.Location stuff.

**Comment by jonathan-s** [comment]
This is no longer the case, since we've upgraded to Django 1.11 for the time being, soon to be upgraded to 2.0 and beyond.
