### ISSUE TITLE
Map on Landing Page is Off

### ISSUE THREAD

**Issue by gardner** [embassynetwork/modernomad#232]
The two flags on this map represent the Red Vic and Haiti. They seem to be more accurate as the zoom level increases.

![screen shot 2015-05-05 at 5 04 36 pm](https://cloud.githubusercontent.com/assets/787026/7484708/0516ba2a-f349-11e4-99e3-122d3c1472d7.png)

**Comment by jessykate** [comment]
duplicate with #282.
