### ISSUE TITLE
Emails should create individual threads per user reservation

### ISSUE THREAD

**Issue by kgstew** [embassynetwork/modernomad#234]
When a user submits a new reservation each individual reservation should have its own thread to manage the approval and confirmation flow. 

Right now the emails all have a generic "Action Required to confirm your reservation" subject line which makes it difficult to track separate conversations and admins regularly duplicate replies to new guests.

Adding a guest name or reservation ID to the subject line would make each thread unique.

**Comment by jessykate** [comment]
thanks @kgstew!!

**Comment by jessykate** [comment]
for proper threading, i wonder if we are not propagating the in-reply-to-header, as discussed [here](http://blog.mailgun.com/tracking-replies-in-mailgun-or-any-other-email/). though regardless, unique subject lines would also be helpful for the humans involved.

**Comment by jessykate** [comment]
this has been working very nicely with the reservation ID in the subject line.
