### ISSUE TITLE
Optimize Tarsnap backups

### ISSUE THREAD

**Issue by jessykate** [embassynetwork/modernomad#293]
We're spending about $3/day and slowly increasing to store daily backups. This could be optimized wrt frequency and contents.

**Comment by gardner** [comment]
The most important thing is to try to restore from the backup before it is necessary. :)

The backup script doesn't seem to be in git. I just setup encrypted duplicity backups for @consciousconsumers using ssh storage as the backend. It supports s3 storage as well. There are some issues with file locks while backing up running systems. If you are able to restore from tarsnap, and it is running well, then $3 / day seems like a reasonable price.

Check out the self-hosted alternatives:
http://duplicity.nongnu.org
https://borgbackup.readthedocs.io
https://news.ycombinator.com/item?id=14796936

**Comment by bfirsh** [comment]
Fixed by #435
