### ISSUE TITLE
Fix behaviour tests

### ISSUE THREAD

**Issue by bfirsh** [embassynetwork/modernomad#302]
They depend on a Saucelabs account that no longer exists. Instead, we can use headless Chrome. That can run inside Docker and on Travis.

**Comment by jonathan-s** [comment]
Do we want selenium tests in the first place, given that they are a bit of an overhead to maintain? I think a first priority should be given to write proper unittests.

**Comment by bfirsh** [comment]
Perhaps. I would argue once things have settled down a bit, some kind of high-level browser tests would be useful.

We could use something other than selenium though. As you say, they are an “overhead” to maintain (I would put it much less politely than that). I have used Cypress before and it has been a much less painful, almost pleasant experience: https://www.cypress.io/

**Comment by bfirsh** [comment]
IIRC the consensus on Slack was to just kill the current behavioural tests and make some more modern ones, as per #339.

Any objections to closing this and making removing all the old tests part of #339?

**Comment by bfirsh** [comment]
cc @jessykate @jonathan-s
