### ISSUE TITLE
Automatic dependency updates

### ISSUE THREAD

**Issue by bfirsh** [embassynetwork/modernomad#305]
Once we've upgraded Python and Django and things have settled down a bit, it might be a good idea to use something to automatically monitor our dependencies. My favourite is Dependabot: https://dependabot.com/

It's particularly useful as a way to get timely security updates, but also useful to keep things up-to-date without much work.

**Comment by bfirsh** [comment]
@jonathan-s @jessykate Any objections to enabling this and seeing what happens? It's going to open loooaaadds of pull requests, but it'd be interesting to see what breaks the test suite and what doesn't. :)

**Comment by bfirsh** [comment]
To be clear: Dependabot doesn't actually change anything, but just opens pull requests for things that can be upgraded.

**Comment by jessykate** [comment]
yes! let's try it!

**Comment by bfirsh** [comment]
💥

**Comment by bfirsh** [comment]
Hooookay. 

Maybe I should disable the JavaScript ones. Everything is so out of date there and we’re not going to update it soon. I could add a ticket to upgrade the JS stuff to the modern world. 

I’ve merged a few very simple ones. Some Python ones are breaking the tests, which is good - it means our tests are finding problems. :)

**Comment by bfirsh** [comment]
Ok disabled JS. 😅
