### ISSUE TITLE
Refactor settings

### ISSUE THREAD

**Issue by jonathan-s** [embassynetwork/modernomad#306]
With the following structure. 
- settings/common.py
- settings/production.py
- settings/staging.py
- settings/local.py

Environment specific setting files import settings from common.py.

**Comment by jessykate** [comment]
In :)

**Comment by bfirsh** [comment]
Perhaps instead we could go full 12-factor and just configure with environment variables. `settings_docker.py` was an attempt at this, which I separated out into a separate file so as not to break existing environments.

**Comment by jonathan-s** [comment]
Yeah, the thought is to make it as much 12 factor as possible. But there still might be some settings that aren't necessarily environment friendly. 

The end result should be a very small files for local, staging and production.py

**Comment by jonathan-s** [comment]
I'll make a PR in the next day or so and we can see where we end up :)
