### ISSUE TITLE
Exception logging in production

### ISSUE THREAD

**Issue by bfirsh** [embassynetwork/modernomad#309]
This will help us track down lots of problems, and aggregate which ones are most common. I like [Sentry](https://sentry.io) but I have no strong opinions.

See also #308.

**Comment by jessykate** [comment]
Sentry reminds me of https://github.com/etsy/statsd which I've been meaning to find an excuse to use. Anyone tried it?

**Comment by jonathan-s** [comment]
At ServerDensity where I used to work we used it coupled with the monitoring software the company were developing.

**Comment by bfirsh** [comment]
For monitoring Heroku apps, I quite like 
https://www.librato.com/ . It’s like statsd + Graphite/Prometheus, but packaged up as a slick service.

**Comment by jessykate** [comment]
#328 effectively addresses this ticket. But would still be cool to wire up some of these other ones in the future! Objections to closing this now?
