### ISSUE TITLE
Re-evaluate what the best way to do static files in Django is

### ISSUE THREAD

**Issue by bfirsh** [embassynetwork/modernomad#344]
We currently use the django compressor library, but I think there might be a better way of doing it now. Worth evaluating and making sure we're not doing anything ancient/overly complex.

**Comment by jonathan-s** [comment]
@bfirsh There are some ideas on how to handle static files here -> https://tech.marksblogg.com/crushing-caching-cdn-django.html and how those files then gets deployed to a cdn. 

Right now the static files are served from django?

**Comment by bfirsh** [comment]
Yes - and serving static files from Django via Whitenoise and Cloudflare is the recommended way to do it on Heroku. Really simple and reliable - no need to do change anything there, I think.

The thing I am interested in is how the static files are generated, and whether we are still doing that the best way (minification, etc).

**Comment by bfirsh** [comment]
We probably want to upgrade whitenoise: https://github.com/embassynetwork/modernomad/pull/421
