### ISSUE TITLE
Fix JS & CSS performance low-hanging fruit

### ISSUE THREAD

**Issue by bfirsh** [embassynetwork/modernomad#377]
- [ ] Load JS at end of body so it doesn't block rendering
- [ ] Bundle all CSS into single file
- [ ] Bundle all JS into single file
- [ ] Perhaps split out `client/` stuff into separate JS bundle, and only load where it is used (or perhaps there is another way to my JS smaller - it is enormous)

<img width="550" alt="screenshot 2019-02-13 at 14 32 17" src="https://user-images.githubusercontent.com/40906/52748755-35787080-2f9c-11e9-9882-18fcd431f69c.png">

Related: #344

**Comment by jonathan-s** [comment]
Where did you get these stats from? A website?

**Comment by bfirsh** [comment]
Google Lighthouse - it's built into Chrome.

**Comment by bfirsh** [comment]
A higher-hanging fruit is merging our two JS systems. There is _so_ much JS, just because some is old jQuery stuff, some is new React stuff, and I vaguely recall there being some mish-mash of the two in there somewhere too.
