### ISSUE TITLE
Offsite backups

### ISSUE THREAD

**Issue by bfirsh** [embassynetwork/modernomad#435]
part of #324
closes #293

**Comment by bfirsh** [comment]
https://github.com/bfirsh/heroku-tarsnap-backups

**Comment by jonathan-s** [comment]
@bfirsh I'm assuming that this script is no longer relevant -> https://github.com/embassynetwork/modernomad/blob/master/modernomad/backup.py

Perhaps it'd be good with a link to the heroku tarsnap backup repo in the documentation and a short blurb on how it is supposed to work. Right now when you search for backup, only that script shows up.

**Comment by bfirsh** [comment]
Yes! That’s a good idea.

**Comment by bfirsh** [comment]
added to https://github.com/embassynetwork/modernomad/issues/322
