### ISSUE TITLE
Browser tests are broken on Linux

### ISSUE THREAD

**Issue by jessykate** [embassynetwork/modernomad#461]
`docker-compose` needs sudo permissions on Linux so are currently broken.

**Comment by bfirsh** [comment]
Implementation ideas in #450.

If there isn't some way to automatically detect, I would argue Docker should be the default (because it is recommended dev environment and how it runs in CI) and there should be an option to run outside of Docker.

**Comment by bfirsh** [comment]
oops dupe of #458
