### ISSUE TITLE
current@ shouldn't be open to everyone

### ISSUE THREAD

**Issue by bfirsh** [embassynetwork/modernomad#532]
I remember getting some spam from current@ while I was a guest and I remember seeing this in Slack somewhere.

Seems like spammers are spamming the current@ email address, and modernomad/mailgun is happily forwarding their emails on to all the guests. This is really bad if we care about deliverability – email servers are going to start considering embassynetwork.com spammy. Once we get stuck in this spam filtered hole, it is very hard to get out, besides completely changing domain.

Is the current@ address used much? If it's not an easy fix, I would argue we just disable this completely ASAP, otherwise other emails are going to get increasingly hard to deliver.

Once we've done this, we should also encourage folks to mark messages as "not spam" if they see anything turn up in a spam filter, which will hopefully undo embassynetwork.com's tarnished reputation. :(

ping @jessykate @jonathan-s because it is relatively time sensitive. :)

**Comment by jonathan-s** [comment]
@bfirsh I've published a PR for this that will only allow someone that is already registered to send to current@. If they are not, it will be silently ignored.

**Comment by bfirsh** [comment]
A potential improvement to this would be to bounce the message so a non-spam sender knows it has been rejected. I think Mailgun lets you do this if you return a particular response.

**Comment by bfirsh** [comment]
Low priority though... it's unclear if anyone actually uses current@...
