### ISSUE TITLE
Offsite Backups

### ISSUE THREAD

**Issue by jsayles** [embassynetwork/modernomad#75]
Every night the machine backs up the database and the media directory but we need to pull them offsite in case the box goes down hard.  Jessy signed up for Tarsnap but it isn't hooked up yet.

**Comment by gardner** [comment]
Based on #293 it sounds like tarsnap is running and we can close this issue.

**Comment by jonathan-s** [comment]
Closing as mentioned by @gardner, but we will review backups soon again anyway so that's another reason to close.

**Comment by bfirsh** [comment]
This is rolled into #324. I’d like to do this as part of that otherwise it’ll never get done...

**Comment by jessykate** [comment]
j'agree. :+1:
